
services:
  task-manager-postgres:
    image: postgres:18.6-bookworm
    container_name: task-manager-env-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
    restart: always

  task-manager-migrate:
    image: migrate/migrate:v4.20.1
    volumes: 
      - ${PROJECT_ROOT}/migrations:/migrations